//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Assets/UI/Player/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/UI/Player/PlayerInput.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""40135480-b5d5-46ef-83e5-74ae1f43544b"",
            ""actions"": [
                {
                    ""name"": ""SelectUnit"",
                    ""type"": ""Button"",
                    ""id"": ""645997c5-9b13-4564-b2ce-f08f57967342"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraMovement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""93b694e7-6d3e-4dbe-b167-faa7af7446f1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ZoomMovement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""fa160b19-4688-45cb-9c83-d3908dd823fa"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryMouseButton"",
                    ""type"": ""Button"",
                    ""id"": ""7893b6da-c8a5-49eb-aabb-09eba0f2829e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SeccondaryMouseButton"",
                    ""type"": ""Button"",
                    ""id"": ""a596ec31-2f7e-4469-8421-27f8a0da09bf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetModifier"",
                    ""type"": ""Button"",
                    ""id"": ""4d6f6838-08f9-4634-9911-af11b142dab8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AdditiveModifier"",
                    ""type"": ""Button"",
                    ""id"": ""41ce82cc-23cf-4108-9559-4221533044e4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AltModifier"",
                    ""type"": ""Button"",
                    ""id"": ""778b3e96-55d9-4340-b16f-e4f8e0e2af6e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryCommand"",
                    ""type"": ""Button"",
                    ""id"": ""fd6b8d2a-6f0c-4e47-9075-0cded4e8fdf9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SeccondaryCommand"",
                    ""type"": ""Button"",
                    ""id"": ""56e95559-a621-49c6-9ef9-cc74d947d0cf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TertiaryCommand"",
                    ""type"": ""Button"",
                    ""id"": ""ef889c63-03c6-4fb6-a2c7-196c052b8ea3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ClearCommands"",
                    ""type"": ""Button"",
                    ""id"": ""03d2bcc3-3bde-4d57-8739-256be0da6824"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionGroup1"",
                    ""type"": ""Button"",
                    ""id"": ""2cf77337-8e1f-47a0-9d99-3d430cf53062"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionGroup2"",
                    ""type"": ""Button"",
                    ""id"": ""fd447215-d626-449b-b451-06ff06026c10"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionGroup3"",
                    ""type"": ""Button"",
                    ""id"": ""a3f6e2b4-df0b-43b1-ae00-c223ee445344"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionGroup4"",
                    ""type"": ""Button"",
                    ""id"": ""da782f30-aec4-416c-9021-025dd9af1dae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionGroup5"",
                    ""type"": ""Button"",
                    ""id"": ""fa1b3438-60e7-4b21-a363-b92c122c22b0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionGroup6"",
                    ""type"": ""Button"",
                    ""id"": ""0a888ceb-c952-4e84-a16c-51d7a5c7abf7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionGroup7"",
                    ""type"": ""Button"",
                    ""id"": ""6d49eebf-1c33-4fee-a754-c3f0c153ef24"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionGroup8"",
                    ""type"": ""Button"",
                    ""id"": ""475ae725-8089-4f6a-bc10-2c316e8ca1c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionGroup9"",
                    ""type"": ""Button"",
                    ""id"": ""c8797031-64ff-4e13-ac9c-f6b120f36614"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionGroup0"",
                    ""type"": ""Button"",
                    ""id"": ""c09cfc06-50eb-4f2e-8c6d-e4ec52e18636"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""fc8d888b-6d33-408f-9341-7e992df2413f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseDelta"",
                    ""type"": ""Value"",
                    ""id"": ""f23f41d9-20dc-454f-a3b9-2bde0f81ac7e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""312f5ec5-2a6d-481e-a96d-e89f92f9b1fa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IncreaseSpeed"",
                    ""type"": ""Button"",
                    ""id"": ""4df65076-f1b5-4061-a38d-8dd467dc0e0c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DecreaseSpeed"",
                    ""type"": ""Button"",
                    ""id"": ""2c28aae6-c38c-4d52-aaaf-7c679c8859ef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PauseSimulation"",
                    ""type"": ""Button"",
                    ""id"": ""94db1995-15fe-4021-9d18-cacbcda54215"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Deselct"",
                    ""type"": ""Button"",
                    ""id"": ""e30f0f1e-b30d-4b42-b0db-0d2c4fe411c3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CenterCamera"",
                    ""type"": ""Button"",
                    ""id"": ""e2151879-2d5a-4b30-b848-a84ffa6c6c5f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FollowUnit"",
                    ""type"": ""Button"",
                    ""id"": ""fa9f7021-1dd7-4aef-857b-d0f0faf2889d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleZoomIndicators"",
                    ""type"": ""Button"",
                    ""id"": ""ac29b12b-7968-4923-9563-7a1a28f6b805"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CombatUnitCommand"",
                    ""type"": ""Button"",
                    ""id"": ""39f2bae7-fe7f-4d45-868c-247ca5a0c7d3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleFactionColors"",
                    ""type"": ""Button"",
                    ""id"": ""0da63da2-28b5-4da8-991c-16d30a0d7dbd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a31cf067-0e68-4dbe-9041-89b3f9e883d2"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""SelectUnit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""5589b2dd-647f-4420-84cd-a0d694920598"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ce8665a0-7313-4437-b0ba-80af801678a7"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d1b0442a-8ebc-4dc5-9467-6297ae87fc16"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8c6faaa0-7737-4eb3-9db0-3c3f6c6b2d48"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""749a3e9c-150a-45e1-bdcc-8a28698a80d4"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d1ce5c56-69af-4b8d-ac4b-db841af1e34b"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""SeccondaryMouseButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""996daaff-4d44-42ae-acda-df40df9857e4"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""PrimaryMouseButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1777a171-12d7-4e89-adde-44f55154b5fe"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""AdditiveModifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99032442-2d1e-43b8-a5a0-e84e5f5ff741"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""ClearCommands"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bde37385-9971-4abe-911c-0ab77780b7cd"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""ActionGroup1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d20b78b-5bdf-4f4b-a886-a47df3a81750"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""ActionGroup2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09efa4f7-7e4c-418b-bfcb-9b039fe1684f"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""ActionGroup3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0916d7bd-5081-4728-ae65-d63c86dbe311"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""ActionGroup4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""01ab59d0-3c94-4d97-8b9b-809742071e78"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""ActionGroup5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""568e9c0a-6c96-4aee-9d1f-78bf4410c89a"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""ActionGroup6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c440dac5-4923-4875-8f92-0ed32930748a"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""ActionGroup7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3fd39df-6056-4360-994f-6f3c43dbc857"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""ActionGroup8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16ced38e-3b99-4c34-989d-6cdd7069ea3c"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""ActionGroup9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5cb8118c-5d40-46a4-9ac1-611e3fe3ba26"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""ActionGroup0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64ab155a-952a-4e4f-b9da-8ace2a2eac87"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""584e1dbc-1321-4114-9f75-d2ca92977633"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""MouseDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22d9620d-89db-4270-91db-8aab754df609"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""ZoomMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""9db1b095-0881-4988-a1af-dfdc5bcaa347"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(y=100)"",
                    ""groups"": """",
                    ""action"": ""ZoomMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f23cdf3f-fdc5-4ef5-adb3-7a0475ada5de"",
                    ""path"": ""<Keyboard>/pageUp"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""ZoomMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a5ce8266-7c4d-41cc-b774-1bbb040d1bb5"",
                    ""path"": ""<Keyboard>/pageDown"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""ZoomMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5f302856-ea82-476c-8632-d63ced15ed09"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""ZoomMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""841cca7a-81ed-4e75-aa1a-606203cde330"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""ZoomMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0a0f66c7-e78c-469f-b93d-19b92c5861b0"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f147e5c8-6779-45e2-a257-243782bcc9e1"",
                    ""path"": ""<Keyboard>/leftAlt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""AltModifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""81532d9b-2b06-4572-b491-867a9c5c16cc"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""SetModifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""012c8dfa-76b1-4f41-8666-1e910db9e3ee"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SeccondaryCommand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a292e9c-1b84-467e-9888-26138e90fe02"",
                    ""path"": ""<Keyboard>/period"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IncreaseSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34f8c89b-4c0f-4958-8f8d-a5dc6e1a897a"",
                    ""path"": ""<Keyboard>/comma"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DecreaseSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""52d91066-88cf-4467-bc15-faa7fa3837c9"",
                    ""path"": ""<Keyboard>/slash"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseSimulation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87ee68dc-65d4-4528-86d1-ec02d9fd0b1b"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryCommand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7287448e-a886-414d-ad36-c7ea6126df65"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TertiaryCommand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6fbc4b26-573f-414c-8f0c-cae9831dde5e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Deselct"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ed92519-71a1-42f2-ae37-839de27cc710"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CenterCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae4764ed-ed75-4b3d-9085-5bd2f915e1c1"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FollowUnit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba73a44e-b789-4e7a-a5d6-a27e8734da5f"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleZoomIndicators"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""175b6979-144f-43cc-a36a-40329e636129"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CombatUnitCommand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0226e264-5dfe-44c0-b3c2-3803f140b35a"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleFactionColors"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard and Mouse"",
            ""bindingGroup"": ""Keyboard and Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_SelectUnit = m_Player.FindAction("SelectUnit", throwIfNotFound: true);
        m_Player_CameraMovement = m_Player.FindAction("CameraMovement", throwIfNotFound: true);
        m_Player_ZoomMovement = m_Player.FindAction("ZoomMovement", throwIfNotFound: true);
        m_Player_PrimaryMouseButton = m_Player.FindAction("PrimaryMouseButton", throwIfNotFound: true);
        m_Player_SeccondaryMouseButton = m_Player.FindAction("SeccondaryMouseButton", throwIfNotFound: true);
        m_Player_SetModifier = m_Player.FindAction("SetModifier", throwIfNotFound: true);
        m_Player_AdditiveModifier = m_Player.FindAction("AdditiveModifier", throwIfNotFound: true);
        m_Player_AltModifier = m_Player.FindAction("AltModifier", throwIfNotFound: true);
        m_Player_PrimaryCommand = m_Player.FindAction("PrimaryCommand", throwIfNotFound: true);
        m_Player_SeccondaryCommand = m_Player.FindAction("SeccondaryCommand", throwIfNotFound: true);
        m_Player_TertiaryCommand = m_Player.FindAction("TertiaryCommand", throwIfNotFound: true);
        m_Player_ClearCommands = m_Player.FindAction("ClearCommands", throwIfNotFound: true);
        m_Player_ActionGroup1 = m_Player.FindAction("ActionGroup1", throwIfNotFound: true);
        m_Player_ActionGroup2 = m_Player.FindAction("ActionGroup2", throwIfNotFound: true);
        m_Player_ActionGroup3 = m_Player.FindAction("ActionGroup3", throwIfNotFound: true);
        m_Player_ActionGroup4 = m_Player.FindAction("ActionGroup4", throwIfNotFound: true);
        m_Player_ActionGroup5 = m_Player.FindAction("ActionGroup5", throwIfNotFound: true);
        m_Player_ActionGroup6 = m_Player.FindAction("ActionGroup6", throwIfNotFound: true);
        m_Player_ActionGroup7 = m_Player.FindAction("ActionGroup7", throwIfNotFound: true);
        m_Player_ActionGroup8 = m_Player.FindAction("ActionGroup8", throwIfNotFound: true);
        m_Player_ActionGroup9 = m_Player.FindAction("ActionGroup9", throwIfNotFound: true);
        m_Player_ActionGroup0 = m_Player.FindAction("ActionGroup0", throwIfNotFound: true);
        m_Player_MousePosition = m_Player.FindAction("MousePosition", throwIfNotFound: true);
        m_Player_MouseDelta = m_Player.FindAction("MouseDelta", throwIfNotFound: true);
        m_Player_Escape = m_Player.FindAction("Escape", throwIfNotFound: true);
        m_Player_IncreaseSpeed = m_Player.FindAction("IncreaseSpeed", throwIfNotFound: true);
        m_Player_DecreaseSpeed = m_Player.FindAction("DecreaseSpeed", throwIfNotFound: true);
        m_Player_PauseSimulation = m_Player.FindAction("PauseSimulation", throwIfNotFound: true);
        m_Player_Deselct = m_Player.FindAction("Deselct", throwIfNotFound: true);
        m_Player_CenterCamera = m_Player.FindAction("CenterCamera", throwIfNotFound: true);
        m_Player_FollowUnit = m_Player.FindAction("FollowUnit", throwIfNotFound: true);
        m_Player_ToggleZoomIndicators = m_Player.FindAction("ToggleZoomIndicators", throwIfNotFound: true);
        m_Player_CombatUnitCommand = m_Player.FindAction("CombatUnitCommand", throwIfNotFound: true);
        m_Player_ToggleFactionColors = m_Player.FindAction("ToggleFactionColors", throwIfNotFound: true);
    }

    ~@PlayerInput()
    {
        UnityEngine.Debug.Assert(!m_Player.enabled, "This will cause a leak and performance issues, PlayerInput.Player.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_SelectUnit;
    private readonly InputAction m_Player_CameraMovement;
    private readonly InputAction m_Player_ZoomMovement;
    private readonly InputAction m_Player_PrimaryMouseButton;
    private readonly InputAction m_Player_SeccondaryMouseButton;
    private readonly InputAction m_Player_SetModifier;
    private readonly InputAction m_Player_AdditiveModifier;
    private readonly InputAction m_Player_AltModifier;
    private readonly InputAction m_Player_PrimaryCommand;
    private readonly InputAction m_Player_SeccondaryCommand;
    private readonly InputAction m_Player_TertiaryCommand;
    private readonly InputAction m_Player_ClearCommands;
    private readonly InputAction m_Player_ActionGroup1;
    private readonly InputAction m_Player_ActionGroup2;
    private readonly InputAction m_Player_ActionGroup3;
    private readonly InputAction m_Player_ActionGroup4;
    private readonly InputAction m_Player_ActionGroup5;
    private readonly InputAction m_Player_ActionGroup6;
    private readonly InputAction m_Player_ActionGroup7;
    private readonly InputAction m_Player_ActionGroup8;
    private readonly InputAction m_Player_ActionGroup9;
    private readonly InputAction m_Player_ActionGroup0;
    private readonly InputAction m_Player_MousePosition;
    private readonly InputAction m_Player_MouseDelta;
    private readonly InputAction m_Player_Escape;
    private readonly InputAction m_Player_IncreaseSpeed;
    private readonly InputAction m_Player_DecreaseSpeed;
    private readonly InputAction m_Player_PauseSimulation;
    private readonly InputAction m_Player_Deselct;
    private readonly InputAction m_Player_CenterCamera;
    private readonly InputAction m_Player_FollowUnit;
    private readonly InputAction m_Player_ToggleZoomIndicators;
    private readonly InputAction m_Player_CombatUnitCommand;
    private readonly InputAction m_Player_ToggleFactionColors;
    /// <summary>
    /// Provides access to input actions defined in input action map "Player".
    /// </summary>
    public struct PlayerActions
    {
        private @PlayerInput m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Player/SelectUnit".
        /// </summary>
        public InputAction @SelectUnit => m_Wrapper.m_Player_SelectUnit;
        /// <summary>
        /// Provides access to the underlying input action "Player/CameraMovement".
        /// </summary>
        public InputAction @CameraMovement => m_Wrapper.m_Player_CameraMovement;
        /// <summary>
        /// Provides access to the underlying input action "Player/ZoomMovement".
        /// </summary>
        public InputAction @ZoomMovement => m_Wrapper.m_Player_ZoomMovement;
        /// <summary>
        /// Provides access to the underlying input action "Player/PrimaryMouseButton".
        /// </summary>
        public InputAction @PrimaryMouseButton => m_Wrapper.m_Player_PrimaryMouseButton;
        /// <summary>
        /// Provides access to the underlying input action "Player/SeccondaryMouseButton".
        /// </summary>
        public InputAction @SeccondaryMouseButton => m_Wrapper.m_Player_SeccondaryMouseButton;
        /// <summary>
        /// Provides access to the underlying input action "Player/SetModifier".
        /// </summary>
        public InputAction @SetModifier => m_Wrapper.m_Player_SetModifier;
        /// <summary>
        /// Provides access to the underlying input action "Player/AdditiveModifier".
        /// </summary>
        public InputAction @AdditiveModifier => m_Wrapper.m_Player_AdditiveModifier;
        /// <summary>
        /// Provides access to the underlying input action "Player/AltModifier".
        /// </summary>
        public InputAction @AltModifier => m_Wrapper.m_Player_AltModifier;
        /// <summary>
        /// Provides access to the underlying input action "Player/PrimaryCommand".
        /// </summary>
        public InputAction @PrimaryCommand => m_Wrapper.m_Player_PrimaryCommand;
        /// <summary>
        /// Provides access to the underlying input action "Player/SeccondaryCommand".
        /// </summary>
        public InputAction @SeccondaryCommand => m_Wrapper.m_Player_SeccondaryCommand;
        /// <summary>
        /// Provides access to the underlying input action "Player/TertiaryCommand".
        /// </summary>
        public InputAction @TertiaryCommand => m_Wrapper.m_Player_TertiaryCommand;
        /// <summary>
        /// Provides access to the underlying input action "Player/ClearCommands".
        /// </summary>
        public InputAction @ClearCommands => m_Wrapper.m_Player_ClearCommands;
        /// <summary>
        /// Provides access to the underlying input action "Player/ActionGroup1".
        /// </summary>
        public InputAction @ActionGroup1 => m_Wrapper.m_Player_ActionGroup1;
        /// <summary>
        /// Provides access to the underlying input action "Player/ActionGroup2".
        /// </summary>
        public InputAction @ActionGroup2 => m_Wrapper.m_Player_ActionGroup2;
        /// <summary>
        /// Provides access to the underlying input action "Player/ActionGroup3".
        /// </summary>
        public InputAction @ActionGroup3 => m_Wrapper.m_Player_ActionGroup3;
        /// <summary>
        /// Provides access to the underlying input action "Player/ActionGroup4".
        /// </summary>
        public InputAction @ActionGroup4 => m_Wrapper.m_Player_ActionGroup4;
        /// <summary>
        /// Provides access to the underlying input action "Player/ActionGroup5".
        /// </summary>
        public InputAction @ActionGroup5 => m_Wrapper.m_Player_ActionGroup5;
        /// <summary>
        /// Provides access to the underlying input action "Player/ActionGroup6".
        /// </summary>
        public InputAction @ActionGroup6 => m_Wrapper.m_Player_ActionGroup6;
        /// <summary>
        /// Provides access to the underlying input action "Player/ActionGroup7".
        /// </summary>
        public InputAction @ActionGroup7 => m_Wrapper.m_Player_ActionGroup7;
        /// <summary>
        /// Provides access to the underlying input action "Player/ActionGroup8".
        /// </summary>
        public InputAction @ActionGroup8 => m_Wrapper.m_Player_ActionGroup8;
        /// <summary>
        /// Provides access to the underlying input action "Player/ActionGroup9".
        /// </summary>
        public InputAction @ActionGroup9 => m_Wrapper.m_Player_ActionGroup9;
        /// <summary>
        /// Provides access to the underlying input action "Player/ActionGroup0".
        /// </summary>
        public InputAction @ActionGroup0 => m_Wrapper.m_Player_ActionGroup0;
        /// <summary>
        /// Provides access to the underlying input action "Player/MousePosition".
        /// </summary>
        public InputAction @MousePosition => m_Wrapper.m_Player_MousePosition;
        /// <summary>
        /// Provides access to the underlying input action "Player/MouseDelta".
        /// </summary>
        public InputAction @MouseDelta => m_Wrapper.m_Player_MouseDelta;
        /// <summary>
        /// Provides access to the underlying input action "Player/Escape".
        /// </summary>
        public InputAction @Escape => m_Wrapper.m_Player_Escape;
        /// <summary>
        /// Provides access to the underlying input action "Player/IncreaseSpeed".
        /// </summary>
        public InputAction @IncreaseSpeed => m_Wrapper.m_Player_IncreaseSpeed;
        /// <summary>
        /// Provides access to the underlying input action "Player/DecreaseSpeed".
        /// </summary>
        public InputAction @DecreaseSpeed => m_Wrapper.m_Player_DecreaseSpeed;
        /// <summary>
        /// Provides access to the underlying input action "Player/PauseSimulation".
        /// </summary>
        public InputAction @PauseSimulation => m_Wrapper.m_Player_PauseSimulation;
        /// <summary>
        /// Provides access to the underlying input action "Player/Deselct".
        /// </summary>
        public InputAction @Deselct => m_Wrapper.m_Player_Deselct;
        /// <summary>
        /// Provides access to the underlying input action "Player/CenterCamera".
        /// </summary>
        public InputAction @CenterCamera => m_Wrapper.m_Player_CenterCamera;
        /// <summary>
        /// Provides access to the underlying input action "Player/FollowUnit".
        /// </summary>
        public InputAction @FollowUnit => m_Wrapper.m_Player_FollowUnit;
        /// <summary>
        /// Provides access to the underlying input action "Player/ToggleZoomIndicators".
        /// </summary>
        public InputAction @ToggleZoomIndicators => m_Wrapper.m_Player_ToggleZoomIndicators;
        /// <summary>
        /// Provides access to the underlying input action "Player/CombatUnitCommand".
        /// </summary>
        public InputAction @CombatUnitCommand => m_Wrapper.m_Player_CombatUnitCommand;
        /// <summary>
        /// Provides access to the underlying input action "Player/ToggleFactionColors".
        /// </summary>
        public InputAction @ToggleFactionColors => m_Wrapper.m_Player_ToggleFactionColors;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerActions" />
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @SelectUnit.started += instance.OnSelectUnit;
            @SelectUnit.performed += instance.OnSelectUnit;
            @SelectUnit.canceled += instance.OnSelectUnit;
            @CameraMovement.started += instance.OnCameraMovement;
            @CameraMovement.performed += instance.OnCameraMovement;
            @CameraMovement.canceled += instance.OnCameraMovement;
            @ZoomMovement.started += instance.OnZoomMovement;
            @ZoomMovement.performed += instance.OnZoomMovement;
            @ZoomMovement.canceled += instance.OnZoomMovement;
            @PrimaryMouseButton.started += instance.OnPrimaryMouseButton;
            @PrimaryMouseButton.performed += instance.OnPrimaryMouseButton;
            @PrimaryMouseButton.canceled += instance.OnPrimaryMouseButton;
            @SeccondaryMouseButton.started += instance.OnSeccondaryMouseButton;
            @SeccondaryMouseButton.performed += instance.OnSeccondaryMouseButton;
            @SeccondaryMouseButton.canceled += instance.OnSeccondaryMouseButton;
            @SetModifier.started += instance.OnSetModifier;
            @SetModifier.performed += instance.OnSetModifier;
            @SetModifier.canceled += instance.OnSetModifier;
            @AdditiveModifier.started += instance.OnAdditiveModifier;
            @AdditiveModifier.performed += instance.OnAdditiveModifier;
            @AdditiveModifier.canceled += instance.OnAdditiveModifier;
            @AltModifier.started += instance.OnAltModifier;
            @AltModifier.performed += instance.OnAltModifier;
            @AltModifier.canceled += instance.OnAltModifier;
            @PrimaryCommand.started += instance.OnPrimaryCommand;
            @PrimaryCommand.performed += instance.OnPrimaryCommand;
            @PrimaryCommand.canceled += instance.OnPrimaryCommand;
            @SeccondaryCommand.started += instance.OnSeccondaryCommand;
            @SeccondaryCommand.performed += instance.OnSeccondaryCommand;
            @SeccondaryCommand.canceled += instance.OnSeccondaryCommand;
            @TertiaryCommand.started += instance.OnTertiaryCommand;
            @TertiaryCommand.performed += instance.OnTertiaryCommand;
            @TertiaryCommand.canceled += instance.OnTertiaryCommand;
            @ClearCommands.started += instance.OnClearCommands;
            @ClearCommands.performed += instance.OnClearCommands;
            @ClearCommands.canceled += instance.OnClearCommands;
            @ActionGroup1.started += instance.OnActionGroup1;
            @ActionGroup1.performed += instance.OnActionGroup1;
            @ActionGroup1.canceled += instance.OnActionGroup1;
            @ActionGroup2.started += instance.OnActionGroup2;
            @ActionGroup2.performed += instance.OnActionGroup2;
            @ActionGroup2.canceled += instance.OnActionGroup2;
            @ActionGroup3.started += instance.OnActionGroup3;
            @ActionGroup3.performed += instance.OnActionGroup3;
            @ActionGroup3.canceled += instance.OnActionGroup3;
            @ActionGroup4.started += instance.OnActionGroup4;
            @ActionGroup4.performed += instance.OnActionGroup4;
            @ActionGroup4.canceled += instance.OnActionGroup4;
            @ActionGroup5.started += instance.OnActionGroup5;
            @ActionGroup5.performed += instance.OnActionGroup5;
            @ActionGroup5.canceled += instance.OnActionGroup5;
            @ActionGroup6.started += instance.OnActionGroup6;
            @ActionGroup6.performed += instance.OnActionGroup6;
            @ActionGroup6.canceled += instance.OnActionGroup6;
            @ActionGroup7.started += instance.OnActionGroup7;
            @ActionGroup7.performed += instance.OnActionGroup7;
            @ActionGroup7.canceled += instance.OnActionGroup7;
            @ActionGroup8.started += instance.OnActionGroup8;
            @ActionGroup8.performed += instance.OnActionGroup8;
            @ActionGroup8.canceled += instance.OnActionGroup8;
            @ActionGroup9.started += instance.OnActionGroup9;
            @ActionGroup9.performed += instance.OnActionGroup9;
            @ActionGroup9.canceled += instance.OnActionGroup9;
            @ActionGroup0.started += instance.OnActionGroup0;
            @ActionGroup0.performed += instance.OnActionGroup0;
            @ActionGroup0.canceled += instance.OnActionGroup0;
            @MousePosition.started += instance.OnMousePosition;
            @MousePosition.performed += instance.OnMousePosition;
            @MousePosition.canceled += instance.OnMousePosition;
            @MouseDelta.started += instance.OnMouseDelta;
            @MouseDelta.performed += instance.OnMouseDelta;
            @MouseDelta.canceled += instance.OnMouseDelta;
            @Escape.started += instance.OnEscape;
            @Escape.performed += instance.OnEscape;
            @Escape.canceled += instance.OnEscape;
            @IncreaseSpeed.started += instance.OnIncreaseSpeed;
            @IncreaseSpeed.performed += instance.OnIncreaseSpeed;
            @IncreaseSpeed.canceled += instance.OnIncreaseSpeed;
            @DecreaseSpeed.started += instance.OnDecreaseSpeed;
            @DecreaseSpeed.performed += instance.OnDecreaseSpeed;
            @DecreaseSpeed.canceled += instance.OnDecreaseSpeed;
            @PauseSimulation.started += instance.OnPauseSimulation;
            @PauseSimulation.performed += instance.OnPauseSimulation;
            @PauseSimulation.canceled += instance.OnPauseSimulation;
            @Deselct.started += instance.OnDeselct;
            @Deselct.performed += instance.OnDeselct;
            @Deselct.canceled += instance.OnDeselct;
            @CenterCamera.started += instance.OnCenterCamera;
            @CenterCamera.performed += instance.OnCenterCamera;
            @CenterCamera.canceled += instance.OnCenterCamera;
            @FollowUnit.started += instance.OnFollowUnit;
            @FollowUnit.performed += instance.OnFollowUnit;
            @FollowUnit.canceled += instance.OnFollowUnit;
            @ToggleZoomIndicators.started += instance.OnToggleZoomIndicators;
            @ToggleZoomIndicators.performed += instance.OnToggleZoomIndicators;
            @ToggleZoomIndicators.canceled += instance.OnToggleZoomIndicators;
            @CombatUnitCommand.started += instance.OnCombatUnitCommand;
            @CombatUnitCommand.performed += instance.OnCombatUnitCommand;
            @CombatUnitCommand.canceled += instance.OnCombatUnitCommand;
            @ToggleFactionColors.started += instance.OnToggleFactionColors;
            @ToggleFactionColors.performed += instance.OnToggleFactionColors;
            @ToggleFactionColors.canceled += instance.OnToggleFactionColors;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerActions" />
        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @SelectUnit.started -= instance.OnSelectUnit;
            @SelectUnit.performed -= instance.OnSelectUnit;
            @SelectUnit.canceled -= instance.OnSelectUnit;
            @CameraMovement.started -= instance.OnCameraMovement;
            @CameraMovement.performed -= instance.OnCameraMovement;
            @CameraMovement.canceled -= instance.OnCameraMovement;
            @ZoomMovement.started -= instance.OnZoomMovement;
            @ZoomMovement.performed -= instance.OnZoomMovement;
            @ZoomMovement.canceled -= instance.OnZoomMovement;
            @PrimaryMouseButton.started -= instance.OnPrimaryMouseButton;
            @PrimaryMouseButton.performed -= instance.OnPrimaryMouseButton;
            @PrimaryMouseButton.canceled -= instance.OnPrimaryMouseButton;
            @SeccondaryMouseButton.started -= instance.OnSeccondaryMouseButton;
            @SeccondaryMouseButton.performed -= instance.OnSeccondaryMouseButton;
            @SeccondaryMouseButton.canceled -= instance.OnSeccondaryMouseButton;
            @SetModifier.started -= instance.OnSetModifier;
            @SetModifier.performed -= instance.OnSetModifier;
            @SetModifier.canceled -= instance.OnSetModifier;
            @AdditiveModifier.started -= instance.OnAdditiveModifier;
            @AdditiveModifier.performed -= instance.OnAdditiveModifier;
            @AdditiveModifier.canceled -= instance.OnAdditiveModifier;
            @AltModifier.started -= instance.OnAltModifier;
            @AltModifier.performed -= instance.OnAltModifier;
            @AltModifier.canceled -= instance.OnAltModifier;
            @PrimaryCommand.started -= instance.OnPrimaryCommand;
            @PrimaryCommand.performed -= instance.OnPrimaryCommand;
            @PrimaryCommand.canceled -= instance.OnPrimaryCommand;
            @SeccondaryCommand.started -= instance.OnSeccondaryCommand;
            @SeccondaryCommand.performed -= instance.OnSeccondaryCommand;
            @SeccondaryCommand.canceled -= instance.OnSeccondaryCommand;
            @TertiaryCommand.started -= instance.OnTertiaryCommand;
            @TertiaryCommand.performed -= instance.OnTertiaryCommand;
            @TertiaryCommand.canceled -= instance.OnTertiaryCommand;
            @ClearCommands.started -= instance.OnClearCommands;
            @ClearCommands.performed -= instance.OnClearCommands;
            @ClearCommands.canceled -= instance.OnClearCommands;
            @ActionGroup1.started -= instance.OnActionGroup1;
            @ActionGroup1.performed -= instance.OnActionGroup1;
            @ActionGroup1.canceled -= instance.OnActionGroup1;
            @ActionGroup2.started -= instance.OnActionGroup2;
            @ActionGroup2.performed -= instance.OnActionGroup2;
            @ActionGroup2.canceled -= instance.OnActionGroup2;
            @ActionGroup3.started -= instance.OnActionGroup3;
            @ActionGroup3.performed -= instance.OnActionGroup3;
            @ActionGroup3.canceled -= instance.OnActionGroup3;
            @ActionGroup4.started -= instance.OnActionGroup4;
            @ActionGroup4.performed -= instance.OnActionGroup4;
            @ActionGroup4.canceled -= instance.OnActionGroup4;
            @ActionGroup5.started -= instance.OnActionGroup5;
            @ActionGroup5.performed -= instance.OnActionGroup5;
            @ActionGroup5.canceled -= instance.OnActionGroup5;
            @ActionGroup6.started -= instance.OnActionGroup6;
            @ActionGroup6.performed -= instance.OnActionGroup6;
            @ActionGroup6.canceled -= instance.OnActionGroup6;
            @ActionGroup7.started -= instance.OnActionGroup7;
            @ActionGroup7.performed -= instance.OnActionGroup7;
            @ActionGroup7.canceled -= instance.OnActionGroup7;
            @ActionGroup8.started -= instance.OnActionGroup8;
            @ActionGroup8.performed -= instance.OnActionGroup8;
            @ActionGroup8.canceled -= instance.OnActionGroup8;
            @ActionGroup9.started -= instance.OnActionGroup9;
            @ActionGroup9.performed -= instance.OnActionGroup9;
            @ActionGroup9.canceled -= instance.OnActionGroup9;
            @ActionGroup0.started -= instance.OnActionGroup0;
            @ActionGroup0.performed -= instance.OnActionGroup0;
            @ActionGroup0.canceled -= instance.OnActionGroup0;
            @MousePosition.started -= instance.OnMousePosition;
            @MousePosition.performed -= instance.OnMousePosition;
            @MousePosition.canceled -= instance.OnMousePosition;
            @MouseDelta.started -= instance.OnMouseDelta;
            @MouseDelta.performed -= instance.OnMouseDelta;
            @MouseDelta.canceled -= instance.OnMouseDelta;
            @Escape.started -= instance.OnEscape;
            @Escape.performed -= instance.OnEscape;
            @Escape.canceled -= instance.OnEscape;
            @IncreaseSpeed.started -= instance.OnIncreaseSpeed;
            @IncreaseSpeed.performed -= instance.OnIncreaseSpeed;
            @IncreaseSpeed.canceled -= instance.OnIncreaseSpeed;
            @DecreaseSpeed.started -= instance.OnDecreaseSpeed;
            @DecreaseSpeed.performed -= instance.OnDecreaseSpeed;
            @DecreaseSpeed.canceled -= instance.OnDecreaseSpeed;
            @PauseSimulation.started -= instance.OnPauseSimulation;
            @PauseSimulation.performed -= instance.OnPauseSimulation;
            @PauseSimulation.canceled -= instance.OnPauseSimulation;
            @Deselct.started -= instance.OnDeselct;
            @Deselct.performed -= instance.OnDeselct;
            @Deselct.canceled -= instance.OnDeselct;
            @CenterCamera.started -= instance.OnCenterCamera;
            @CenterCamera.performed -= instance.OnCenterCamera;
            @CenterCamera.canceled -= instance.OnCenterCamera;
            @FollowUnit.started -= instance.OnFollowUnit;
            @FollowUnit.performed -= instance.OnFollowUnit;
            @FollowUnit.canceled -= instance.OnFollowUnit;
            @ToggleZoomIndicators.started -= instance.OnToggleZoomIndicators;
            @ToggleZoomIndicators.performed -= instance.OnToggleZoomIndicators;
            @ToggleZoomIndicators.canceled -= instance.OnToggleZoomIndicators;
            @CombatUnitCommand.started -= instance.OnCombatUnitCommand;
            @CombatUnitCommand.performed -= instance.OnCombatUnitCommand;
            @CombatUnitCommand.canceled -= instance.OnCombatUnitCommand;
            @ToggleFactionColors.started -= instance.OnToggleFactionColors;
            @ToggleFactionColors.performed -= instance.OnToggleFactionColors;
            @ToggleFactionColors.canceled -= instance.OnToggleFactionColors;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />.
        /// </summary>
        /// <seealso cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />
        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerActions.AddCallbacks(IPlayerActions)" />
        /// <seealso cref="PlayerActions.RemoveCallbacks(IPlayerActions)" />
        /// <seealso cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />
        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerActions" /> instance referencing this action map.
    /// </summary>
    public PlayerActions @Player => new PlayerActions(this);
    private int m_KeyboardandMouseSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme KeyboardandMouseScheme
    {
        get
        {
            if (m_KeyboardandMouseSchemeIndex == -1) m_KeyboardandMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard and Mouse");
            return asset.controlSchemes[m_KeyboardandMouseSchemeIndex];
        }
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Player" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerActions.AddCallbacks(IPlayerActions)" />
    /// <seealso cref="PlayerActions.RemoveCallbacks(IPlayerActions)" />
    public interface IPlayerActions
    {
        /// <summary>
        /// Method invoked when associated input action "SelectUnit" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelectUnit(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CameraMovement" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCameraMovement(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ZoomMovement" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnZoomMovement(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PrimaryMouseButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPrimaryMouseButton(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SeccondaryMouseButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSeccondaryMouseButton(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SetModifier" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSetModifier(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "AdditiveModifier" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAdditiveModifier(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "AltModifier" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAltModifier(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PrimaryCommand" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPrimaryCommand(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SeccondaryCommand" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSeccondaryCommand(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TertiaryCommand" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTertiaryCommand(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ClearCommands" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnClearCommands(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ActionGroup1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnActionGroup1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ActionGroup2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnActionGroup2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ActionGroup3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnActionGroup3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ActionGroup4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnActionGroup4(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ActionGroup5" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnActionGroup5(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ActionGroup6" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnActionGroup6(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ActionGroup7" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnActionGroup7(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ActionGroup8" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnActionGroup8(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ActionGroup9" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnActionGroup9(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ActionGroup0" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnActionGroup0(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MousePosition" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMousePosition(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MouseDelta" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMouseDelta(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Escape" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnEscape(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "IncreaseSpeed" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIncreaseSpeed(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "DecreaseSpeed" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDecreaseSpeed(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PauseSimulation" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPauseSimulation(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Deselct" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDeselct(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CenterCamera" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCenterCamera(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "FollowUnit" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFollowUnit(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ToggleZoomIndicators" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleZoomIndicators(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CombatUnitCommand" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCombatUnitCommand(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ToggleFactionColors" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleFactionColors(InputAction.CallbackContext context);
    }
}
