name: Deploy

on:
  workflow_run:
    workflows: [ Build and Test ]
    branches: [ main ]
    types:
      - completed
  workflow_dispatch:

jobs:
  none:
    name: Deploy to WebGL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Build-WebGL
          github-token: ${{ github.token }}
#          run-id: ${{ github.event.workflow_run.id }}
          run-id: 16326265425
          path: build/WebGL
      - name: push build
        run: |
          git clone https://github.com/tuvus/tuvus.github.io.git
          cd tuvus.github.io
          git config --unset-all http.https://github.com/.extraheader
          git config user.name "WebGLDeployer"
          git checkout -b "deployversion"
          rm -rf Build/
          cp ../build/WebGL/Build Build/
          git add Build/
          git remote -v
          git push --set-upstream origin deployversion
          git push
