name: Deploy

on:
  workflow_run:
    workflows: [ Build and Test ]
    branches: [ main ]
    types:
      - completed
  workflow_dispatch:

jobs:
  none:
    name: Deploy to WebGL
    runs-on: ubuntu-latest
    steps:
      - name: Get Run ID
        id: get-run-id
        run: |
          RUN_ID=`gh run --repo ${{ github.repository }} list --workflow "Build and Test" --json databaseId --jq .[0].databaseId`
          echo "Detected latest run id of ${RUN_ID} for workflow Buld and Test"
          echo "run-id=${RUN_ID}" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: actions/download-artifact@v4
        with:
          name: Build-WebGL
          github-token: ${{ github.token }}
          run-id: ${{ steps.get-run-id.outputs.run-id }}
          repository: ${{ github.repository }}
          path: build/WebGL
      - uses: actions/download-artifact@v4
        with:
          name: LatestVersion
          github-token: ${{ github.token }}
          run-id: ${{ steps.get-run-id.outputs.run-id }}
          repository: ${{ github.repository }}
          path: .
      - name: push build
        run: |
          ls -l
          LATEST_VERSION=`cat version.txt`
          echo "Version: ${LATEST_VERSION}"
          git clone https://github.com/tuvus/tuvus.github.io.git
          cd tuvus.github.io
          git config user.name "Oskar Niesen"
          git config user.email "oskarniesen1@gmail.com"
          rm -rf Build/
          cp -r ../build/WebGL/WebGL/Build Build/
          sed -i 's/<!--versionstart-->.*<!--vesionend-->/<!--versionstart-->v${LATEST_VERSION}<!--vesionend-->/' index.html
          git add .
          git commit -m "Deploy version ${LATEST_VERSION}"
          echo "Pushing to master version ${LATEST_VERSION}"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/tuvus/tuvus.github.io.git
          git push
